### ISSUE TITLE
Multiple Grids Not Rendering Properly

### ISSUE THREAD

**Issue by Evaske** [saleel/react-native-super-grid#17]
So this is a bit of an odd one... I have a tabbed navigation consisting of three tabs, each page identical apart from the data being fed in to the list. The first two tabs that are mounted display perfectly but the third and subsequent lists don't display anything unless I first scroll up or down slightly. Only then, do the grid items appear.

Now I have gotten around this by adding the following property to the list view which seems to fix it:
`removeClippedSubviews={false}`

Any ideas what could be causing this? I'm using react-native-router-flux for the navigation and just a simple image as the components to render on the list.

**Comment by saleel** [comment]
Not sure. Maybe this is related to [PR #16](https://github.com/saleel/react-native-super-grid/issues/16)

From the [docs](https://facebook.github.io/react-native/docs/scrollview.html#removeclippedsubviews) this property is true by default and offscreen elements are removed. The tabbed navigation component could be using overflow hidden or something. 

I guess your issue is solved for now with that prop. Don't want to change the main code for now. I am planning to switch from ListView to FlatList and all these issues might go on its own.
