### ISSUE TITLE
Ability to render a grid inside an existing ScrollView

### ISSUE THREAD

**Issue by slorber** [saleel/react-native-super-grid#38]
Hi,

Current implementation always use a FlatList.

It's like to reuse the grid abilities of this lib but just render items as-is without providing an extra scrollable container.

My usecase is to render a list of photos (small amount, no virtualization needed) as a responsive grid inside an existing scrollable container (which also has a parallax header animation). The grid is not the only element of this scrollview and I can't really use a FlatList header for that.

**Comment by saleel** [comment]
All the additional props you pass to GridView are passed on to the FlatList inside. FlatList support all props of ScrollView as well. So you can disable scroll behaviour of the GridView.

You should also be able to set the height (dynamically) of contents inside the FlatList/GridView so that you parent ScrollView will always display the entire grid.
