### ISSUE TITLE
Is it possible to have every section with only one scrollable row of items?

### ISSUE THREAD

**Issue by pani7** [saleel/react-native-super-grid#78]
Is it possible to have every section with one scrollable row of items, not arranging them in multiple rows if they take more space than width of screen?

I need to have up to 200 sections containing only one row with 180 items and i need this 180 items to be arranged in one scrollable row, not to arrange them in multiple rows as it is done by default.

I tried with using 1 flatList as a data for each section but that makes ui very slow.

Is there a solution for this?

Thank you

**Comment by saleel** [comment]
Its not possible with this library. Also this is not in the scope of this lib as your requirement is not a GridView.

Your implementation could be slow because you are loading all the data at one. There are ways to load data dynamically in to SectionList and FlatList, you can try those (try `onEndReached` prop in FlatList).
